repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.1 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
    - id: terraform_fmt
      files: ^terraform/.*\.tf$
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/terraform/.tflint.hcl
